"""Regression: sliced print files populate and remain attached to print records."""
import io
import json
import os
import sys
import tempfile
import zipfile
from pathlib import Path

from fastapi.testclient import TestClient

root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root))
data_dir = Path(tempfile.mkdtemp(prefix="layervault-toolpath-job-"))
os.environ["DATA_DIR"] = str(data_dir)

from app.main import TOOLPATH_DIR, TOOLPATH_UPLOAD_DIR, app  # noqa: E402

client = TestClient(app)
assert client.get("/health").json() == {"ok": True, "version": "0.3.29", "schema": 128}

gcode = b"""; generated by OrcaSlicer 2.3
; filament used [mm] = 1000
; filament_diameter = 1.75
; filament_density = 1.24
; estimated printing time (normal mode) = 1h 2m 30s
; layer_height = 0.2
; temperature = 210
; bed_temperature = 60
; perimeter_speed = 45
; fill_density = 15%
; wall_loops = 3
M109 S210
M190 S60
G1 X10 Y10 E1
"""

inspection = client.post(
    "/api/jobs/toolpath/inspect",
    files={"file": ("bluebell-quality.gcode", gcode, "text/x-gcode")},
)
assert inspection.status_code == 200, inspection.text
metadata = inspection.json()
assert metadata["slicer"] == "OrcaSlicer"
assert metadata["duration_minutes"] == 63
assert metadata["filament_length_mm"] == 1000
assert abs(metadata["material_volume_ml"] - 2.405) < 0.001
assert abs(metadata["material_weight_g"] - 2.982) < 0.001
assert metadata["volume_estimated"] is True
assert metadata["settings"]["layer_height_mm"] == 0.2
assert metadata["settings"]["nozzle_temp_c"] == 210
assert metadata["settings"]["bed_temp_c"] == 60
assert metadata["settings"]["infill_percent"] == 15
assert (TOOLPATH_UPLOAD_DIR / f"{metadata['token']}.gcode").exists()

material = client.post("/api/materials", json={
    "name": "PLA test spool", "kind": "Filament", "material": "PLA", "unit": "g",
    "initial_amount": 1000, "remaining_amount": 1000, "density_g_cm3": 1.24,
}).json()
created = client.post("/api/jobs", json={
    "name": "Bluebell sliced job", "material_id": material["id"], "status": "Queued",
    "toolpath_token": metadata["token"], "settings_snapshot": {"print_speed_mms": 50},
})
assert created.status_code == 200, created.text
job = created.json()
assert job["duration_minutes"] == 63
assert abs(job["material_used"] - 2.982) < 0.001
assert job["toolpath_original_name"] == "bluebell-quality.gcode"
assert job["toolpath_size_bytes"] == len(gcode)
assert job["toolpath_metadata"]["slicer"] == "OrcaSlicer"
assert job["settings_snapshot"]["layer_height_mm"] == 0.2
assert job["settings_snapshot"]["print_speed_mms"] == 50
stored = TOOLPATH_DIR / job["toolpath_file"]
assert stored.exists() and stored.read_bytes() == gcode
assert not (TOOLPATH_UPLOAD_DIR / f"{metadata['token']}.gcode").exists()
download = client.get(f"/api/jobs/{job['id']}/toolpath")
assert download.status_code == 200 and download.content == gcode
assert "bluebell-quality.gcode" in download.headers["content-disposition"]

# 3MF/PM3 containers are inspected as bounded ZIP metadata rather than treated as raw text.
container = io.BytesIO()
with zipfile.ZipFile(container, "w", zipfile.ZIP_DEFLATED) as archive:
    archive.writestr("Metadata/Slic3r_PE.config", """; generated by PrusaSlicer
filament used [cm3] = 4.75
filament used [g] = 5.89
layer_height = 0.15
temperature = 205
""")
three_mf = client.post(
    "/api/jobs/toolpath/inspect",
    files={"file": ("plate.3mf", container.getvalue(), "application/vnd.ms-package.3dmanufacturing-3dmodel+xml")},
)
assert three_mf.status_code == 200, three_mf.text
assert three_mf.json()["slicer"] == "PrusaSlicer"
assert three_mf.json()["material_volume_ml"] == 4.75
assert three_mf.json()["material_weight_g"] == 5.89

assert client.delete(f"/api/jobs/{job['id']}").json() == {"ok": True}
assert not stored.exists()
print("LayerVault v0.3.29 sliced-file inspection, auto-log and attachment regression: PASS")
